verbose: False
dataset: 'tartanair'
mode: 'mono'
stride: 1
mapping:
  device: "cuda:0"
  bound: [[-10.0, 10.0], [-10.0, 10.0], [-10.0, 10.0]]

tracking:
  device: "cuda:0"
  buffer: 500
  beta: 0.7
  warmup: 12
  upsample: True
  motion_filter:
    thresh: 5.0  # add as keyframe if avg flow >= 4.0 pixels
  multiview_filter:
    thresh: 0.01  # depth error < 0.01m
    visible_num: 2  # points viewed by at least 2 cameras
    kernel_size: inf
    bound_enlarge_scale: 1.20
  frontend:
    thresh: 20.0 
    radius: 1
    window: 40 
    nms: 0
  backend:
    thresh: 30.0  
    radius: 2
    nms: 2
    # used for loop detection
    loop_window: 250
    loop_thresh: 30.0  
    loop_radius: 2
    loop_nms: 5

cam:
  ### original camera parameters
  H: 480
  W: 640
  fx: 320.0
  fy: 320.0
  cx: 320.0
  cy: 240.0
  ### target/output camera settings, camera_size -> resize -> crop -> target_size
  H_edge: 0
  W_edge: 0
  H_out: 480
  W_out: 640

rendering:
  N_samples: 24
  N_surface: 48

meshing:
  eval_rec: True
  resolution: 512  # change to 512 for higher resolution geometry
  get_largest_components: False
  remove_small_geometry_threshold: 0.2
  n_points_to_eval: 200000
  mesh_threshold_to_eval: 0.05
  forecast_radius: 25


data:
  input_folder: /media/data/TartanAir/seasidetown/Easy/P000
  output: ""