inherit_from: configs/ScanNet/scannet_mono.yaml
mode: mono
mapping:
  device: "cuda:0"
  bound: [[-5, 14.0],[-4.0,5.0],[-6, 4]]
meshing:
  gt_mesh_path: '/home/yzhang/data/ScanNet/scans/scene0181_00/scene0181_00_vh_clean.ply'
data:
  input_folder: /home/yzhang/data/ScanNet/scans/scene0181_00
  output: /home/yzhang/exps/goslam/scannet/0181/mono
