inherit_from: configs/ScanNet/scannet_mono.yaml
mode: mono
mapping:
  device: "cuda:0"
  bound: [[-0.9,7.3],[-1.0,9.6],[-1.0,3.7]]
meshing:
  gt_mesh_path: '/home/yzhang/data/ScanNet/scans/scene0059_00/scene0059_00_vh_clean.ply'
data:
  input_folder: /home/yzhang/data/ScanNet/scans/scene0059_00
  output: /home/yzhang/exps/goslam/scannet/0059/mono
