inherit_from: ./configs/ScanNet/scannet_mono.yaml
mode: mono
mapping:
  device: "cuda:0"
  bound: [[-4, 5], [-3, 6], [-3, 6]]

meshing:
  gt_mesh_path: '/home/yzhang/data/ScanNet/scans/scene0233_00/scene0233_00_vh_clean.ply'

data:
  input_folder: /home/yzhang/data/ScanNet/scans/scene0233_00
  output: /home/yzhang/exps/goslam/scannet/0233/mono
