inherit_from: configs/ScanNet/scannet_mono.yaml
mode: mono
mapping:
  device: "cuda:0"
  bound: [[-10, 10],[-10, 10],[-10, 10]]
data:
  input_folder: /media/data/ScanNet/scans/scene0106_00
  output: ""
