inherit_from: ./configs/ScanNet/scannet.yaml
mode: rgbd
mapping:
  device: "cuda:0"
  bound: [[-6, 4], [-6, 5], [-4, 5]]

meshing:
  gt_mesh_path: '/media/data/ScanNet/scans/scene0465_00/scene0465_00_vh_clean.ply'

data:
  input_folder: /media/data/ScanNet/scans/scene0465_00
  output: ""
