name: go-slam
channels:
  - rusty1s
  - pytorch
  - nvidia
  - open3d-admin
  - conda-forge
  - defaults
dependencies:
  - pytorch-scatter
  - torchaudio # - torchvision
  - pytorch=2.1
  - cudatoolkit
  - tensorboard
  - scipy
  - opencv
  - tqdm
  - suitesparse
  - matplotlib
  - pyyaml
  - ffmpeg
  - kiwisolver
  - ninja
  - numpy
  - pillow
  - pyqt
  - tk
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - open3d # This package is actually trouble when installing under conda instead of pip
  - pip:
    - PyOpenGL-acclerate Installing this manually works, using conda does not
    - dask
    - gdown
    - imageio
    - networkx
    - pandas
    - trimesh
    - termcolor
    - webencodings
    - pyrender
