inherit_from: configs/EuRoC/euroc.yaml
mode: stereo
only_tracking: False
mapping:
  bound: [[-10, 10], [-10, 10], [-10, 10]]
data:
  input_folder: /home/yzhang/data/EuRoC/V1_01_easy
  # output: /home/yzhang/exps/goslam/euroc/V1_02_medium/voxel1024v2
  output: /home/yzhang/exps/goslam/scannet/supplementary/V1_01_easy/stereo_r25
