inherit_from: configs/EuRoC/euroc.yaml
mode: stereo
only_tracking: False
mapping:
  bound: [[-10, 10], [-10, 10], [-10, 20]]
data:
  input_folder: /home/yzhang/data/EuRoC/V2_02_medium
  output: /home/yzhang/exps/goslam/euroc/V2_02_medium
