inherit_from: configs/Replica/replica.yaml
mode: rgbd
mapping:
  bound: [[-5.0, 5.0], [-5.0, 5.0], [-5.0, 5.0]]
meshing:
  gt_mesh_path: /home/yzhang/data/Replica/cull_replica_meshv2/office1.ply
data:
  input_folder: /home/yzhang/data/Replica/office1
  output: /home/yzhang/exps/goslam/Replica/office1/rgbd