inherit_from: configs/Replica/replica_mono.yaml
mode: mono
mapping:
  bound: [[-2.0, 2.0], [-2.0, 2.0], [-2.0, 2.0]]
meshing:
  gt_mesh_path: /home/yzhang/data/Replica/cull_replica_meshv2/room2.ply
data:
  input_folder: /home/yzhang/data/Replica/room2
  output: /home/yzhang/exps/goslam/Replica/room2/mono
