inherit_from: configs/Replica/replica_mono.yaml
mode: mono
mapping:
  bound: [[-2.0, 2.0], [-2.0, 2.0], [-2.0, 2.0]]
meshing:
  gt_mesh_path: /media/data/Replica/cull_replica_meshv2/room1.ply
data:
  input_folder: /media/data/Replica/room1
  output: ""
