inherit_from: configs/Replica/replica.yaml
mode: rgbd
mapping:
  bound: [[-5.0, 5.0], [-5.0, 5.0], [-5.0, 5.0]]
meshing:
  gt_mesh_path: /media/data/Replica/cull_replica_meshv2/room0.ply
data:
  input_folder: /media/data/Replica/room0
  output: ""
