## Feature detector 
method: eigen
### Available trained models are: 
# ResNet18 (with output dim 256 or 512)
# ResNet50 (output dim 128, 256, 512 or 2048), 
# ResNet101 (output dim 128, 256, 512 or 2048)
# VGG16 (output dim 512)
model: ResNet50
fc_output_dim: 2048
k_nearest: 10 # Only look at the topk nearest neighbors in the database to speed up the search

## Thresholds for considering loops
threshold: 0.6 # Threshold for frame distance, i.e. candidate pairs should have distance < threshold
min_temporal_distance: 10 # Keyframes should be at least this far apart for a valid loop closure candidate
max_orientation_difference: 25.0 # Rotation difference in degrees (avg over rpy axis) of the estimated keyframe poses
# This is used for e.g. motion between frames or feature distance

# 2D Keypoint Detector
# NOTE a problem for long-term outdoor slam for us, is that we can only run on a lower resolution without memory
detector_window: 5 # DPVO: 15
score_threshold: 30.0 # DPVO: 40.0
min_num_inliers: 5 # At least have 10 keypoints for matching

### 3D Matching 
triplet_stride: 1 # Stride for triplet triangulation
max_2d_residual: 2.0 # Max. 2D residual [px] for 2d keypoint matching and 3d backprojection
# RANSAC
perc_inliers: 0.25 # Inlier percentage for RANSAC
# RANSAC uses the 3D distance between points here
# NOTE on KITTI, we often have good candidates with 15% points < 0.8m
ransac_thresh: 0.4 # The threshold depends on the scene scale!
ransac_iters: 600
max_depth: 30.0 # Only use 3D keypoints < max_depth 
nms: 15 # Suppression for redundant matches (The smaller, the closer loops are allowed to be)

# Loop Closure edge management
check_consecutive: True # Check for consecutive frames
n_repeat: 3 # Loop closures are only valid, if they have k consecutive detections

# Pose Graph Optimization hyperparameters
# (Idea: We simply add new segments to an already optimized map that should be untouched from drift)
fix_segments: True # Fix some segments during optimization 
free_segments: 3 # Number of last n-i segments that are free to optimize every PGO