defaults:
  - /loop_closure/base@_here_

method: eigen

### Available trained models are: 
# ResNet18 (with output dim 256 or 512)
# ResNet50 (output dim 128, 256, 512 or 2048), 
# ResNet101 (output dim 128, 256, 512 or 2048)
# VGG16 (output dim 512)
model: ResNet50
fc_output_dim: 2048
threshold: 0.5 # Score threshold for feature distance (0.5 is good for l2)
k_nearest: 10 # Only look at the topk nearest neighbors in the database to speed up the search


