defaults:
  - /loop_closure/base@_here_

max_2d_residual: 2.0 # Max. 2D residual [px] for 2d keypoint matching and 3d backprojection
# RANSAC
perc_inliers: 0.25 # Inlier percentage for RANSAC
# RANSAC uses the 3D distance between points here
# NOTE on KITTI, we often have good candidates with 15% points < 0.8m
ransac_thresh: 0.4 # The threshold depends on the scene scale!
ransac_iters: 600
max_depth: 30.0 # Only use 3D keypoints < max_depth 
nms: 15 # Suppression for redundant matches (The smaller, the closer loops are allowed to be)
