warmup: 15 # Wait until tracking gets to this frame
delay: 2 # Delay between tracking and mapping
mapping_iters: 10 # Optimization iterations for selected views
refinement_iters: 50 # Final Optimization iterations for all views
use_gui: True
batch_mode: True # Only update a constant sized batch of frames
save_renders: False
use_spherical_harmonics: False

filter_depth: False # TODO activate this option
filter_uncertainty: False # TODO

optimize_poses: False
update_frames: True # TODO when is this used?

init_lr: 6.0

# Strategy for adding / pruning Gaussians
keyframes:
  n_last_frames: 5 # Always optimize the last n frames
  n_rand_frames: 5 # Optimize random global frames on top
  default_batch_size: 3 # Only add 5 frames at once to increase latency when batch_mode is deactivated
  prune_every: 15 # How often to prune gaussians
  visibility_th: 5 # Gaussians should be pruned based on covisibility
  prune_last: 5

  filter: # Parameter for filtering incoming points from the SLAM system
    mv_count_thresh: 2 # Pixels need to be consistent within bin_thresh distance across these k views
    bin_thresh: 0.1
    confidence_thresh: 0.1 # Only take pixels above this confidence

  mapping:
    densify_grad_threshold: 0.0002
    size_threshold: 20
    gaussian_th: 0.005
    gaussian_extent: 10

  refinement:
    densify_grad_threshold: 0.0002
    size_threshold: 20
    gaussian_th: 0.5
    gaussian_extent: 2


opt_params:
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.01

  cam_rot_delta: 0.0003
  cam_trans_delta: 0.0001

loss:
  alpha: 0.95 # Size of the mapping loss that the rgb takes up, the rest is depth
  beta: 5.0 # Regularizer on scale changes of the Gaussians
  rgb_boundary_threshold: 0.01 # Pixel information in an image needs to be at least higher than this 

# Parameters for transfer SLAM -> Renderer
input:
  sensor_type: 'depth'
  pcd_downsample: 64
  pcd_downsample_init: 32
  adaptive_pointsize: True
  point_size: 0.05
  type: 'replica'

pipeline_params:
  convert_SHs_python: False
  compute_cov3D_python: False
