defaults:
  - /mapping/base@_here_

# Online Optimization
online_opt:
  # Local sliding optimization window
  iters: 100 # Optimization iterations for selected views
  n_last_frames: 10 # Always optimize the last n frames
  n_rand_frames: 20 # Optimize random global frames on top

  prune_every: 4 # Prune every k Render passes
  pruning:
    use_covisibility: True
    covisibility:
      mode: "new" # ["abs", "new"] How to prune: either check for covisible frames everywhere or just in the last n frames
      last: 10 # Prune only Gaussians added during the last k frames (Hint: this needs to be <= n_last_frames)
      visibility_th: 2 # Gaussians not visible by at least this many frames are pruned

  prune_densify_every: 25 # This uses i) vanilla split and clone from 3DGS and ii) opacity based densification
  prune_densify_until: 55 # dont do this after this iteration
  ## Densification parameters
  densify:
    # Vanilla 3DGS splitting and densification strategy
    vanilla:
      max_grad: 0.001 # Gaussians with gradients above this are split (smaller -> denser)
      extent: 5  # Gaussians with scale smaller than self.percent_dense * extent get cloned (bigger -> denser)
      min_opacity: 0.05 # Gaussians with opacity lower than this get pruned (bigger -> more pruning)
      max_screen_size: 15 # Gaussians with radius bigger than this get pruned (smaller -> more pruning)
      scale_std: 1.0 # How much variance when perturbating old Gaussians during densify_and_split()

  # How to Filter the Tracking Map before feeding into Mapper
  filter: # Parameter for filtering incoming points from the SLAM system
    multiview: True # Only initialize Gaussians that are consistent in multiple views
    mv_count_th: 2 # Pixels need to be consistent within bin_thresh distance across these k views
    # NOTE these are in relation to the mean of the distribution
    bin_th: 0.05 # Distance between points for binning, this depends on the scene scale, so be careful!
    uncertainty: False # Only use very certain points for intializing Gaussians

opt_params:
  position_lr_init: 1e-3 # Default MonoGS: 0.00016 (RGB mode has x10)
  position_lr_final: 5e-4 # Default MonoGS: 0.0000016
  position_lr_max_steps: 100 # Default MonoGS: 30000

loss:
  # Weights
  supervise_with_prior: True # Use the prior for supervision. If not, then use the current filtered map from SLAM (Hint: this is usually better as metrics are computed on all pixels)
  alpha1: 0.8 # Size of the mapping loss that the rgb takes up, the rest is depth (default: 0.95)
  alpha2: 0.2 # Weight SSIM and L1 loss (default 0.85 is common in monocular depth estimation)
  beta1: 5.0 # Regularizer on isotropic scale of the Gaussians (bigger -> more isotropic)
  beta2: 0.001 # Edge-aware smoothness loss for depth (default 0.001 is common in monocular depth estimation)

# Parameters for transfer SLAM -> Renderer
input:
  pcd_downsample_init: 64 # This is a constant downsampling factor
  pcd_downsample: 64 # You ideally have ~5-10k points per frame
  point_size: 0.02
