defaults:
  - gaussian

mapping_iters: 100 # At each new frame, 10 views
refinement_iters: 100 # Once at the end, all views

opt_params:
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.05
  scaling_lr: 0.001
  rotation_lr: 0.001
  percent_dense: 0.01

  cam_rot_delta: 0.00003
  cam_trans_delta: 0.00001


keyframes:
  prune_every: 30
  visibility_th: 5
  prune_last: 5

  mapping:
    densify_grad_threshold: 0.00005
    size_threshold: 15
    opacity_th: 0.05

  refinement:
    gaussian_extent: 3



