defaults:
  - base

buffer: 512
warmup: 12

motion_filter:
  thresh: 5.0  # add as keyframe if avg flow >= 4.0 pixels

frontend:
  thresh: 20.0 
  window: 40 
  radius: 1
  nms: 0
  release_cache: True 

backend:
  thresh: 30.0  
  radius: 2
  nms: 2

  use_loop_closure: False
  loop_window: 250
  loop_thresh: 30.0  
  loop_radius: 2
  loop_nms: 5