pretrained: ./pretrained/droid.pth
buffer: 1500  # 256
beta: 0.5  # beta * Distance(R|t) + (1-beta) * Distance(I|t), refer to droid_kernels.cu:frame_distance_kernel 
warmup: 8
upsample: False # True

motion_filter:
  thresh: 2.4  # Consider new keyframe with motion >

frontend:
  optimize_scales: True # Whether or not to optimize scale of prgbd prior
  steps1: 4 # 1st outer loop with feature correlation
  steps2: 2 # 2nd loop with feature correlation
  iters: 4 # Actual BA iterations
  # NOTE this is actually much more important than the window in order to keep many frames in the local optimization!
  # NOTE this slows down the system a lot, since you increase the number of factors drastically
  max_age: 25 # (default: 25) Max age of a factor, we remove these after optimizing them for so long in the current window

  keyframe_thresh: 4.0 # remove keyframe if avg flow < 
  thresh: 16.0 # Add edges between frames within this distance
  window: 25 # local ba window size
  max_factors: 150 # num of edges within local ba
  radius: 2 # Always build edges between nearby frames
  nms: 1

  # NOTE: Warning. This can slightly change results as well for some reason
  release_cache: False # Tradeoff: memory vs. speed, This can save up to ~5GB
  
backend:
  warmup: 15
  do_refinement: True # Do we want to refine the map afterwards with backend?
  window: 150 # Dont optimize more keyframes to avoid OOM
  thresh: 22.0 # Add edges between frames within this distance
  max_factor_mult: 16
  radius: 2
  nms: 3

  use_loop_closure: False
  # NOTE make sure that loop window is not bigger than the general window of the backend
  loop_window: 40 # Default GO-SLAM: 25
  loop_thresh: 50.0 # You want this one to be big, so we add enough edges for loops
  loop_radius: 5 # Default GO-SLAM: 1
  loop_nms: 12 # Default GO-SLAM: 12
  loop_max_factor_mult: 16