defaults:
  - /tracking/base@_here_

buffer: 1500 
warmup: 8
beta: 0.5  # beta * Distance(R|t) + (1-beta) * Distance(I|t), refer to droid_kernels.cu:frame_distance_kernel 
# Running mapping and higher resolutions requires either more Memory or other tricks
upsample: False # Without upsampling memory management is suddenly possible

motion_filter:
  thresh: 5.0  # add as keyframe if avg flow >

frontend:
  optimize_scales: True # Whether or not to optimize scale of prgbd prior
  steps1: 4 # 1st outer loop with feature correlation
  steps2: 2 # 2nd loop with feature correlation
  # NOTE: Turns out we need more iterations for convergence on outdoor scenes
  iters: 6 # Actual BA iterations
  keyframe_thresh: 6.0  # remove keyframe if avg flow < 
  thresh: 20.0  # only consider edge with avg flow < 
  window: 40  # local ba window size
  release_cache: True 
  max_age: 25 # (default: 25) Max age of a factor, we remove these after optimizing them for so long in the current window
  pose_interpolation: damped # linear (linear motion w. const speed), damped (damped linear motion), naive/null (just copy the prev pose)

backend:
  warmup: 15
  thresh: 60.0  # only consider edge with avg flow < 
  window: 600 # Dont optimize more keyframes to avoid OOM
  filter_edges: True # Filter out low confidence edges
  radius: 1
  max_factor_mult: 3
  nms: 1 # The higher this is, the fewer factors are build