defaults:
  - /tracking/base@_here_

warmup: 12

frontend:
  thresh: 16.0  
  window: 25  # local ba window size

backend:
  thresh: 20.0  # only consider edge with avg flow < x pixels
  nms: 0

  steps: 4
  iters: 2

  use_loop_closure: True
  loop_window: 100
  loop_thresh: 20.0  # only consider edge with avg flow < x pixels
  loop_radius: 1
  loop_nms: 5