defaults:
  - /tracking/base@_here_

warmup: 12
sleep_delay: 1.0 # Time delay to synchronize frontend and backend (default: 2.0)

frontend:
  thresh: 10.0  
  window: 25  # local ba window size

backend:
  warmup: 12
  window: 100 # Dont optimize more keyframes to avoid OOM
  thresh: 15.0  # only consider edge with avg flow < 
  radius: 2
  nms: 2

  use_loop_closure: True
  loop_thresh: 15.0  # only consider edge with avg flow < x pixels
  loop_window: 150
  loop_radius: 2
  loop_nms: 5