pretrained: ./pretrained/droid.pth
buffer: 512 # 1024
beta: 0.5  # beta * Distance(R|t) + (1-beta) * Distance(I|t), refer to droid_kernels.cu:frame_distance_kernel 
warmup: 8
upsample: True
motion_filter:
  thresh: 4.0  # add as keyframe if avg flow >:  4.0 pixels


multiview_filter:
  thresh: 0.01  # depth error < 0.01m
  visible_num: 2  # points viewed by at least 2 cameras
  kernel_size: inf
  bound_enlarge_scale: 1.20


frontend:
  steps1: 4 # 1st outer loop with feature correlation
  steps2: 2 # 2nd outer loop with feature correlation
  iters: 4 # Actual BA iterations
  keyframe_thresh: 4.0  # remove keyframe if avg flow < 4.0 pixels
  thresh: 16.0  
  window: 25  # local ba window size
  max_factors: 100  # num of edges within local ba
  radius: 2
  nms: 1

  use_loop_closure: False
  loop_window: 100
  loop_thresh: 20.0  # only consider edge with avg flow < x pixels
  loop_radius: 1
  loop_nms: 12

  release_cache: False # Tradeoff: memory vs. speed, This can save up to ~5GB

  
backend:
  warmup: null
  window: 200 # Dont optimize more keyframes to avoid OOM
  thresh: 25.0  # only consider edge with avg flow < x pixels
  radius: 1
  nms: 5

  steps: 8
  iters: 2

  use_loop_closure: False
  loop_window: 100
  loop_thresh: 20.0  # only consider edge with avg flow < x pixels
  loop_radius: 1
  loop_nms: 12