defaults:
  - /tracking/base@_here_

beta: 0.5

motion_filter:
  thresh: 4.0  # Consider new keyframe with motion >

frontend:
  max_age: 20

backend: 
  warmup: 25
  window: 150
  max_factor_mult: 16
  thresh: 60.0
  radius: 2
  nms: 2
